
#ifndef CTRLIDS_H
#define CTRLIDS_H

/// menuIDs for BFDirCtrl and BFBackupTree
#define BFBACKUPCTRL_ID_ADDDESTINATION      1 + wxID_HIGHEST
#define BFBACKUPCTRL_ID_COPY_DIR            2 + wxID_HIGHEST
#define BFDIRCTRL_ID_BACKUP_DIRCOPY         BFBACKUPCTRL_ID_COPY_DIR
#define BFBACKUPCTRL_ID_COPY_FILE           3 + wxID_HIGHEST
#define BFDIRCTRL_ID_BACKUP_FILECOPY        BFBACKUPCTRL_ID_COPY_FILE
#define BFDIRCTRL_ID_FILEBUTTON             4 + wxID_HIGHEST
#define BFDIRCTRL_ID_ADDDESTINATION         5 + wxID_HIGHEST
#define BFDIRCTRL_ID_CREATEDESTINATION      6 + wxID_HIGHEST
#define BFBACKUPCTRL_ID_CREATEDESTINATION   7 + wxID_HIGHEST
#define BFBACKUPCTRL_ID_MACROBUTTON         8 + wxID_HIGHEST
#define BFBACKUPCTRL_ID_SYNC_DIR            9 + wxID_HIGHEST
#define BFDIRCTRL_ID_BACKUP_SYNCDIR         BFBACKUPCTRL_ID_SYNC_DIR
#define BFMACROBUTTON_ID_PRESSED            10 + wxID_HIGHEST
#define BFMACROBUTTON_ID_MACRO_DATE         11 + wxID_HIGHEST
#define BFBACKUPCTRL_ID_PROJECTSETTINGS     12 + wxID_HIGHEST

#endif  // CTRLIDS_H
