-------------------------------------------------------------------------------
                              ==== BUILD ====

                              -- BLACKFISK --
                            Version 0.0.0 alpha
-------------------------------------------------------------------------------

contact on other build-env, architectures

build-env step by step
