-------------------------------------------------------------------------------
                              ==== BUILD ====

                              -- BLACKFISK --
                            Version 0.0.0 alpha
-------------------------------------------------------------------------------

Blackfisk want to support all plattforms, architectures and build environments!
Please contact me if you need support for a undescribed plattform, architecture
or build environment.

Windows, MinGW, Code::Blocks
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1. Download the GNU based compiler system for Windows from
   <http://www.mingw.org> and install it.
2. Get the wxWidgets sources from <http://www.wxwidgets.org> and build it.
3. Download the IDE Code::Blocks from <http://www.codeblocks.org>
   and install it.
4. Open the workspace file "BF.workspace" with Code::Blocks.
5. Go to the menu "Settings/Global variables..." and set the variables
   #wx and #wxversion.
6. Then select the correct build target in the menu "Build/Select target".
   Which target you need depends on the configuration (debug, release,
   static, dynamic) you build wxWidgets.
7. Just build blackfisk with the menu entry "Build/Build and run".

More detailes and help
~~~~~~~~~~~~~~~~~~~~~~
Please feel free to contact me if you need more help to build blackfisk!
